# Generated by Django 4.2 on 2023-04-09 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.seller')),
            ],
        ),
    ]
