# Generated by Django 4.2 on 2023-04-09 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('order_type', models.CharField(choices=[('DEP', 'Deposit'), ('WIT', 'Withdraw')], default='DEP', max_length=3)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.seller')),
            ],
        ),
    ]
