# Generated by Django 4.2 on 2023-04-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_creditorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
