# Generated by Django 4.2 on 2023-04-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEP', 'Deposit'), ('WIT', 'Withdraw'), ('SALE', 'Sale')], default='SALE', max_length=4),
        ),
    ]
