# Generated by Django 4.2 on 2023-04-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditorder',
            name='status',
            field=models.CharField(choices=[('COM', 'Completed'), ('FAI', 'Failed')], default='FAI', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('COM', 'Completed'), ('FAI', 'Failed')], default='FAI', max_length=3),
        ),
        migrations.AlterField(
            model_name='seller',
            name='credit',
            field=models.PositiveBigIntegerField(),
        ),
    ]
