# Generated by Django 4.2 on 2023-04-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_alter_creditorder_status_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditorder',
            name='status',
            field=models.CharField(choices=[('COM', 'Completed'), ('FAI', 'Failed'), ('PEN', 'Pending')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('COM', 'Completed'), ('FAI', 'Failed'), ('PEN', 'Pending')], default='PEN', max_length=3),
        ),
    ]
